service: serverless-graphql-chat

provider:
  name: aws
  runtime: nodejs4.3

functions:
  api:
    handler: handler.graphql
    memorySize: 256
    timeout: 6
    events:
    - http:
        path: graphql
        method: post
        integration: lambda
        request:
          parameters:
            #headers:
            #  foo: false
            #  bar: true
            paths:
              query: true           # required post parameter
              variables: false      # optional post parameter
              operationName: false  # optional post parameter